### ISSUE TITLE
chroot to a dir based on remote_user variable

### ISSUE THREAD

**Issue by marcurdy** [ZenProjects/Apache-mod-chroot#1]
I'm looking to create an https interface that allows uploads and downloads from a directory based on the authenticated user and not a static document root.  Can that be supported with the current implementation?

**Comment by mcarbonneaux** [comment]
actualy is not possible...

And is complicated with the apache architecture (worker, event, prefork model)...

Beceause they need root to use chroot, and when you have chrooted (made in childinit phase of apache), you cannot dechroot, and you are oblige to exit from the child process to do that...

And this have big impact on performance, because they generate to many fork...

you must use chroot to more global directory that englobe all user directory, and after use apache alias/rewrite to virtualise arborescance or php/jsp script to virtualise abrorescance...

**Comment by mcarbonneaux** [comment]
like that module : 
https://httpd.apache.org/docs/2.4/en/howto/public_html.html

**Comment by marcurdy** [comment]
Thanks.  I'm looking for the easiest way to implement a safe https upload by avoiding the usual security pitfalls that involves too much server-side validation of the upload.  I'm not attached to httpd, but that's my first go-to.
